Process Process-1:
Traceback (most recent call last):
  File "/Users/fionaspuler/opt/anaconda3/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/fionaspuler/opt/anaconda3/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/fionaspuler/Documents/GitHub/isimipy/notebooks/isimip3basd-master/code/bias_adjustment.py", line 654, in load_or_save_one_location
    item = from_pool_queue.get()
NameError: name 'from_pool_queue' is not defined
Traceback (most recent call last):
  File "/Users/fionaspuler/Documents/GitHub/isimipy/notebooks/isimip3basd-master/code/bias_adjustment.py", line 999, in <module>
    main()
  File "/Users/fionaspuler/Documents/GitHub/isimipy/notebooks/isimip3basd-master/code/bias_adjustment.py", line 969, in main
    adjust_bias(
  File "/Users/fionaspuler/Documents/GitHub/isimipy/notebooks/isimip3basd-master/code/bias_adjustment.py", line 714, in adjust_bias
    with mp.Pool(n_processes-1, initializer, (ipq,)) as pool:
  File "/Users/fionaspuler/opt/anaconda3/lib/python3.9/multiprocessing/context.py", line 119, in Pool
    return Pool(processes, initializer, initargs, maxtasksperchild,
  File "/Users/fionaspuler/opt/anaconda3/lib/python3.9/multiprocessing/pool.py", line 212, in __init__
    self._repopulate_pool()
  File "/Users/fionaspuler/opt/anaconda3/lib/python3.9/multiprocessing/pool.py", line 303, in _repopulate_pool
    return self._repopulate_pool_static(self._ctx, self.Process,
  File "/Users/fionaspuler/opt/anaconda3/lib/python3.9/multiprocessing/pool.py", line 326, in _repopulate_pool_static
    w.start()
  File "/Users/fionaspuler/opt/anaconda3/lib/python3.9/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/Users/fionaspuler/opt/anaconda3/lib/python3.9/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/Users/fionaspuler/opt/anaconda3/lib/python3.9/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/Users/fionaspuler/opt/anaconda3/lib/python3.9/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/Users/fionaspuler/opt/anaconda3/lib/python3.9/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/Users/fionaspuler/opt/anaconda3/lib/python3.9/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'adjust_bias.<locals>.initializer'
